#!groovy

// Generated by IBM TransformationAdvisor
// Mon Jul 08 09:47:49 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}